---
language: node_js
node_js:
  - 'stable'
env:
  secure: X1xB2Bkmx8lLlXJC798YjKVIOD3tOjSXmQyoMfCSmLIV+3xVw/oyzvjFD508h1X+t0/HpS1gapn0IEO53gJUYVsIMLuZcdF6kbHb2M70aFLzbp+Q6cwzf1ivjXBTPtKFKO2klie8zobfnDabzWnHG18L32Oz4rI7CQ2OodMHP8cJevZKkN1vMs8vYZtmQ+DYIAh+q5/TpW6TrunrAjgAmnDctWM5hzqK8efTl43dxnnoEgpFeaM1T/PVSGopm2qCrYuYViVRU6FPvT5grg7E4s3vYVQZnVkCWbc1zA+ra4nW5rg77qPBEd3Mi09tkIH8Pwx/SGq6uecsXQk+C6GtQl0kM2GRjLaDngTagLS3jQ9rq+NFKAheDl3UXZdzWiaPNHgltmmWQLfwPrj5DYQW1UD2+YynYD5UI00ERHzbTl1MsX953yfcsz+b3Buc55JTnUmorKUxS8M+Z22NEfBGwaB1QzrZo+F0ccfFEtZKohTml6RSnFkMZjPHhXWE4TdvzWaO4OTR5hHkaYFVkplVC5jd1HGHQlGDcAKyxpoGYGCKdNLXI91vQk5hs51UuIXEIwhC+ANvExOr/3ctL9e+7wEmQRQpEnBsCNJ2YFRj25C94f56aJjtEjGYrgYOS5PuknQcsQKmdk+72wTrOag5zHldiV1Ib3dHUbp/de5y9Ow=
cache: yarn
script:
  - yarn lint
  - yarn test
  - yarn generate
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master
notifications:
  email: false
  slack:
    secure: jrmFAeACji+Ln+FiKdx5BzLj23yGKoXFChgjxXDTC3lsaN9TCzFf38IxP0ROCxbPBkM35VUrfXZrHy7hC6puz18IgkUseIyU/WpsIKE5JiEagyv4YX/yjWM7GrwUPEAymmqZR0mv35aZ+rPewyWp4wOUy1p4BbKPIAwzy34oDE8yE5T1yO9LJ20qkHVL7ZPpR2VgR4AoTQgQME21mdB5VZYWV3yEse9oDFJbVfchTvdnOs1TvcqUX3i/ApospNmaOeqyol8ZTlF2JciiZDyaS2LsIyA/OKBoT72AYF+Q+XfR0JECOdd6I7C8HbZz2T81sPkH/UZLDSjESIWTaONyRqAAGJ2ot7iryb19M82gz5wSxN74VNLP/jWpnBu9IOEk8PvJCaxO9aUditxxm3W5WVx3MzruWKQ4yhGletNeSohEsEluxcz5osJN+JX4oW0boicNEpEQPwKk/gKgADfPCGFKfcySG+3K2DVWPcyu91w6uFc7jiUe+Tyoe25tkGipFevbmF4c+wpqlmCWZXTeWSSjiYJklA17fqpTXHEmIBf5PN9WJRf947GyFUK9PSDan3NP4I75r99cmfCbLMkPFzIRxk5xamOGF+bK30JAH5Drq5wiwrtZy/vJU6maMRFIH+HPDth9Z0zjhjxY1CEDpMe0wBk0ObhG2wfr8strf9E=
